spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/crm
    username: root
    password: password

  tenant:
    datasource:
      url-prefix: jdbc:mysql://localhost:3306/
      username: root
      password: password
      pool:
        maximum-pool-size: 2
        minimum-idle: 1
        driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: G9MzZjTz2Mm89rL1RL9Jb9vP0rf4pKukwH3XzOvQduE=

server:
  port: 8082

logging:
  level:
    com.zen.auth: DEBUG
