spring:
  application:
    name: crm-service

  datasource:
    url: jdbc:mysql://localhost:3306/crm
    username: root
    password: password
    pool:
        maximum-pool-size: 2
        minimum-idle: 1
        driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          multiTenancy: SCHEMA
          tenant_identifier_resolver: com.zen.crm.filters.CurrentTenantIdentifierResolverImpl
          multi_tenant_connection_provider: com.zen.crm.filters.MultiTenantConnectionProviderImpl

server:
  port: 8083

logging:
  level:
    com.zen.crm: DEBUG
